### ISSUE TITLE
Missing xml files deps!

### ISSUE THREAD

**Issue by AndreasHeine** [umati/Sample-Server-asyncio#29]
If there arent present on purpose we should at least document where they can find them!

```
Start setup...
Setup done! 2.037533760070801s
Importing companion spec. XML...
[Errno 2] No such file or directory: 'c:\\Users\\HeineAn\\Downloads\\Sample-Server-asyncio-develop\\Sample-Server-asyncio-develop\\deps\\UA-Nodeset\\DI\\Opc.Ua.Di.NodeSet2.xml'
Traceback (most recent call last):
  File "c:/Users/HeineAn/Downloads/Sample-Server-asyncio-develop/Sample-Server-asyncio-develop/src/server.py", line 233, in <module>
    asyncio.run(main())
  File "C:\Users\HeineAn\AppData\Local\Programs\Python\Python37-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\HeineAn\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:/Users/HeineAn/Downloads/Sample-Server-asyncio-develop/Sample-Server-asyncio-develop/src/server.py", line 65, in main
    di_idx = await server.get_namespace_index("http://opcfoundation.org/UA/DI/")
  File "C:\Users\HeineAn\AppData\Local\Programs\Python\Python37-32\lib\site-packages\asyncua\server\server.py", line 471, in get_namespace_index
    return uries.index(uri)
ValueError: 'http://opcfoundation.org/UA/DI/' is not in list
```

**Comment by GoetzGoerisch** [comment]
Is this the lastest develop? I introduce an error with #22 but fixed it with #26 .
